version: "3"

services:
  fastbot-ros2-real:
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-real
    container_name: fastbot-ros2-real
    privileged: true
    cap_add:
      - NET_ADMIN
    network_mode: host
    ipc: host
    environment:
      # Match host defaults (no host changes needed):
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      # If you don’t use GUI, you can omit DISPLAY/XAUTHORITY completely.
      # - DISPLAY=${DISPLAY}
      # - XAUTHORITY=${XAUTHORITY}
    devices:
      - /dev/video0:/dev/video0
      - /dev/lslidar:/dev/lslidar
      - /dev/arduino_nano:/dev/arduino_nano
    # Remove Cyclone config (we're using Fast DDS now):
    # volumes:
    #   - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
    restart: always
    # Ensure something actually starts:
    command: >
      bash -lc "
      source /opt/ros/humble/setup.bash &&
      source /ros2_ws/install/setup.bash 2>/dev/null || true &&
      ros2 launch fastbot_bringup bringup.launch.xml
      "

  fastbot-ros2-slam-real:
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-slam-real
    container_name: fastbot-ros2-slam-real
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      # - DISPLAY=${DISPLAY}
      # - XAUTHORITY=${XAUTHORITY}
    # volumes:
    #   - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
    restart: always
    command: >
      bash -lc "
      source /opt/ros/humble/setup.bash &&
      source /ros2_ws/install/setup.bash 2>/dev/null || true &&
      ros2 launch fastbot_slam cartographer.launch.py
      "
