# dockerfile-ros2-real  (ARM64-friendly)
FROM ros:humble-ros-base
# FROM arm64v8/ros:humble-ros-base-jammy
# FROM arm64v8/ros:humble-ros-base

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Tools + deps for building and running SLAM
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions build-essential \
    ros-humble-cartographer-ros \
    ros-humble-robot-state-publisher \
    ros-humble-tf2-ros \
    ros-humble-slam-toolbox \
    ros-humble-nav2-bringup \
    ros-humble-navigation2 \
    ros-humble-rviz2 \
    ros-humble-cartographer \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-cyclonedds \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws/src
# Copy packages into the image (paths are relative to BUILD CONTEXT)
RUN git clone https://github.com/bhmoon713/fastbot_description_cp22.git fastbot_description  && \
    git clone https://github.com/bhmoon713/fastbot_slam.git
# COPY fastbot/fastbot_description/ src/fastbot_description/
# COPY fastbot/ src/fastbot

# NOTE: Because WORKDIR is /ros2_ws/src, use destinations without a leading "src/"
# COPY fastbot/map_server/           map_server/
# COPY fastbot/localization_server/  localization_server/
# COPY fastbot/fastbot_slam/         fastbot_slam/

# Ensure Gazebo classic model path exists before copying
RUN mkdir -p /usr/share/gazebo-11/models/fastbot_description && \
    cp -a /ros2_ws/src/fastbot_description/. /usr/share/gazebo-11/models/fastbot_description/


# Build the Colcon workspace and ensure it's sourced
WORKDIR /ros2_ws
RUN source /opt/ros/humble/setup.bash && colcon build
RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

# If you want to expose your workspace packages as models, add the workspace src to the model path
# (set base first, then append existing if present)
ENV GAZEBO_MODEL_PATH=/ros2_ws/src:${GAZEBO_MODEL_PATH}

# Source Humble + overlay and launch navigation
# ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam navigation.launch.py"]
ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"]
