version: "3"

services:
  fastbot-ros2-real:
    # build:
    #   context: ${HOME}/ros2_ws/src
    #   dockerfile: fastbot_ros2_docker/real/dockerfile-ros2-real
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-real
    container_name: fastbot-ros2-real
    network_mode: host          # <— THE big one
    ipc: host                   # optional; avoids some SHM surprises
    privileged: true            # optional, but common on real robots
    
    cap_add:
      - NET_ADMIN
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0    # <— don’t confine to loopback
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
    devices:
      - /dev/video0:/dev/video0
      - /dev/lslidar:/dev/lslidar
      - /dev/arduino_nano:/dev/arduino_nano
      # # Likely your Arduino Nano (CDC ACM):
      # - /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A6D016743-if00:/dev/arduino_nano
      # # Likely your LiDAR (CH340 USB-serial):
      # - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/lslidar
      # # Camera passthrough as before:
      # - /dev/video0:/dev/video0
      # - /dev/video0:/dev/video0
      # - /dev/ttyACM0:/dev/ttyACM0
      # - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
    privileged: true
    restart: always

    # networks:
    #   - fastbot_net


  fastbot-ros2-slam-real:
    # build:
    #   context: ${HOME}/ros2_ws/src
    #   dockerfile: fastbot_ros2_docker/real/dockerfile-ros2-slam-real
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-slam-real
    container_name: fastbot-ros2-slam-real
    network_mode: host          # <— THE big one
    ipc: host                   # optional; avoids some SHM surprises
    privileged: true            # optional, but common on real robots

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}    
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0 
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
#     networks:
#       - fastbot_net

# networks:
#   fastbot_net:
