version: "3"

services:
  fastbot-ros2-real:
    build:
      context: ${HOME}/ros2_ws/src
      dockerfile: fastbot_ros2_docker/real/dockerfile-ros2-real
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-real
    container_name: fastbot-ros2-real
    cap_add:
      - NET_ADMIN
    environment:
      - XAUTHORITY=${XAUTHORITY}       
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    devices:
      - /dev/video0:/dev/video0
      - /dev/lslidar:/dev/lslidar
      - /dev/arduino_nano:/dev/arduino_nano
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
    privileged: true
    restart: always

    networks:
      - fastbot_net


  fastbot-ros2-slam-real:
    build:
      context: ${HOME}/ros2_ws/src
      dockerfile: fastbot_ros2_docker/real/dockerfile-ros2-slam-real
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-slam-real
    container_name: fastbot-ros2-slam-real
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}    
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/etc/cyclonedds.xml:ro
    networks:
      - fastbot_net

networks:
  fastbot_net:
