version: "3"

services:
  fastbot-ros2-webapp:
    build:
      context: ${HOME}/ros2_ws/src
      dockerfile: fastbot_ros2_docker/simulation/dockerfile-webapp
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-webapp
    container_name: nginx_container
    hostname: nginx_container
    restart: always
    volumes:
      - ${HOME}/ros2_ws/src/fastbot_webapp:/usr/share/nginx/html:ro
      - logs:/var/log/nginx
      # remove or create this file to avoid compose errors
      # - ${HOME}/no-file.txt:/no-file.txt
    ports:
      - "7000:80"

  fastbot-ros2-gazebo:
    build:
      context: ${HOME}/ros2_ws/src
      dockerfile: fastbot_ros2_docker/simulation/dockerfile-gazebo
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-gazebo
    privileged: true
    cap_add:
      - NET_ADMIN
    container_name: fastbot-ros2-gazebo
    # network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  fastbot-ros2-slam:
    build:
      context: ${HOME}/ros2_ws/src
      dockerfile: fastbot_ros2_docker/simulation/dockerfile-slam
    image: bhmoon418/bhmoon713-cp22:fastbot-ros2-slam
    container_name: fastbot-ros2-slam
    # network_mode: host
    depends_on:
      - fastbot-ros2-gazebo

volumes:
  logs: {}
