FROM osrf/ros:humble-desktop-full

# Sim dependencies you likely need
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions build-essential \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-xacro \
    ros-humble-robot-state-publisher \
    ros-humble-joint-state-publisher-gui \
    && rm -rf /var/lib/apt/lists/*

# Create workspace inside the image
WORKDIR /ros2_ws

# Copy your packages INTO the image (paths are relative to the BUILD CONTEXT)
# Build context will be ~/ros2_ws/src so 'fastbot/...' exists.
COPY fastbot/fastbot_description/ src/fastbot_description/
COPY fastbot/fastbot_gazebo/      src/fastbot_gazebo/


# Build the workspace
RUN bash -lc "source /opt/ros/humble/setup.bash && colcon build --symlink-install"

ENV GAZEBO_MODEL_PATH=/ros2_ws/src/fastbot_gazebo/models:/ros2_ws/src/fastbot_description/models:/usr/share/gazebo-11/models:$GAZEBO_MODEL_PATH
ENV GAZEBO_RESOURCE_PATH=/ros2_ws/src/fastbot_gazebo:$GAZEBO_RESOURCE_PATH

# Always source Humble + your overlay when the container runs
ENTRYPOINT ["/bin/bash","-lc"]
CMD ["source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_gazebo one_fastbot_room.launch.py"]
