FROM osrf/ros:humble-desktop-full

# Tools + deps for building and running SLAM
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions build-essential \
    ros-humble-cartographer-ros \
    ros-humble-robot-state-publisher \
    ros-humble-tf2-ros \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws

# Copy your packages into the image (paths are relative to BUILD CONTEXT)
# Keep description too in case your launch/xacro uses it
COPY fastbot/fastbot_slam/        src/fastbot_slam/
COPY fastbot/fastbot_description/ src/fastbot_description/

# Build the overlay workspace
RUN bash -lc "source /opt/ros/humble/setup.bash && colcon build --symlink-install"

# Source Humble + overlay and launch Cartographer
ENTRYPOINT ["/bin/bash","-lc"]
CMD ["source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam pathplanner.launch.py"]
