FROM osrf/ros:humble-desktop
ENV DEBIAN_FRONTEND=noninteractive

# Use bash for RUN steps
SHELL ["/bin/bash", "-c"]

# System deps (keep one layer)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      apt-utils \
      nginx \
      python3-pip \
      python3-colcon-common-extensions \
      python3-setuptools \
      python3-pytest \
      python3-numpy \
      ros-humble-rosbridge-server \
      ros-humble-web-video-server \
      ros-humble-rosbridge-suite && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-cyclonedds

# Optional: forward nginx logs to Docker logs
# RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
#    ln -sf /dev/stderr /var/log/nginx/error.log

# Workspace (only if you really need colcon later; safe to keep)
WORKDIR /ros2_ws/src

# Your files (adjust paths to your build context)
COPY fastbot_ros2_docker/simulation/entrypoint.sh /entrypoint.sh
COPY fastbot_webapp/ /var/www/html/

# Make entrypoint executable
RUN chmod +x /entrypoint.sh

# (Optional) simple healthcheck on nginx
#HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD curl -f http://localhost/ || exit 1

# Ports: 80 (nginx), 9090 (rosbridge), 8080 (web_video_server)
EXPOSE 80 9090 8080


ENTRYPOINT ["/bin/bash"]
CMD ["/entrypoint.sh"]

