FROM osrf/ros:humble-desktop

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Tools + deps for building and running SLAM
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions build-essential \
    ros-humble-cartographer-ros \
    ros-humble-robot-state-publisher \
    ros-humble-tf2-ros \
    ros-humble-slam-toolbox \
    ros-humble-nav2-bringup \
    ros-humble-navigation2 \
    ros-humble-rviz2 \
    ros-humble-cartographer \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-cyclonedds


WORKDIR /ros2_ws

# Copy your packages into the image (paths are relative to BUILD CONTEXT)
# Keep description too 
COPY fastbot/fastbot_slam/        src/fastbot_slam/
COPY fastbot/fastbot_description/ src/fastbot_description/

# Build the Colcon workspace and ensure it's sourced
RUN source /opt/ros/humble/setup.bash \
 && cd /ros2_ws \
 && colcon build
RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

# Source Humble + overlay and launch navigation
ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam navigation.launch.py"]